const metadata = {
	name: "Tassia Connect",
	parentCompany: {
		name: "Pickaxe & Shovel",
		link: "https://pickaxe-and-shovel.vercel.app/",
	},
};

const dummyPosts = [
	{
		id: 1,
		type: "deal",
		pinned: true,
		title: "50% off the Jordans at sneaker world!",
		content:
			"Step into the game with the iconic Jordans – Style #AJ23. Sleek design, unbeatable comfort, and that legendary streetwear edge. Special Price: Only for this week! Hurry – stock is flying off fast! Own the look. Own the legend. DM now to secure your pair before they’re gone!",
		profiles: {
			full_name: "Sneaker World",
		},
		created_at: "2024-06-01T10:00:00Z",
	},
	{
		id: 2,
		type: "deal",
		pinned: true,
		title: "50% off the Jordans at sneaker world!",
		content:
			"Step into the game with the iconic Jordans – Style #AJ23. Sleek design, unbeatable comfort, and that legendary streetwear edge. Special Price: Only for this week! Hurry – stock is flying off fast! Own the look. Own the legend. DM now to secure your pair before they’re gone!",
		profiles: {
			full_name: "Sneaker World",
		},
		created_at: "2024-06-01T10:00:00Z",
	},
];

const dummyCategories = [
	{
		id: 1,
		slug: "food-drinks",
		color: "#990055",
		name: "Food & Drinks",
		icon: "UtensilsCrossed",
	},
	{
		id: 2,
		slug: "salon-beauty",
		color: "pink",
		name: "Saloon & Beauty",
		icon: "Scissors",
	},
	{
		id: 3,
		slug: "hardware-building",
		color: "orange",
		name: "Hardware & Building",
		icon: "Wrench",
	},
	{
		id: 4,
		slug: "pharmacy-health",
		color: "green",
		name: "Pharmacy & Health",
		icon: "Pill",
	},
	{
		id: 5,
		slug: "electronics-repair",
		color: "blue",
		name: "Electronics & Repair",
		icon: "Smartphone",
	},
	{
		id: 6,
		slug: "grocery",
		color: "#aaddaa",
		name: "Grocery & Supermarket",
		icon: "ShoppingBasket",
	},
	{
		id: 7,
		slug: "laundry",
		color: "#aaaadd",
		name: "Laundry Services",
		icon: "Wind",
	},
	{
		id: 8,
		slug: "medical-clinic",
		color: "purple",
		name: "Medical & Clinic",
		icon: "Stethoscope",
	},
	{
		id: 9,
		slug: "street-food",
		color: "#990033",
		name: "Street & Food & Snacks",
		icon: "Coffee",
	},
	{
		id: 10,
		slug: "financial",
		color: "purple",
		name: "Financial Services",
		icon: "Banknote",
	},
	{
		id: 11,
		slug: "clothing-fashion",
		color: "orange",
		name: "Clothing & Fashion",
		icon: "Shirt",
	},
	{
		id: 12,
		slug: "education",
		color: "green",
		name: "Education & Training",
		icon: "BookOpen",
	},
];

const dummyBusinesses = [
	{
		id: 1,
		slug: "pickaxe-and-shovel",
		name: "Pickaxe & Shovel",
		featured: true,
		categories: {
			name: "Electronics & Repair",
			color: "#2563eb",
			slug: "electronics-repair",
		},
		tagline: "Reliable gadget repairs and electronics accessories.",
		cover_image:
			"https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
		average_rating: 5,
		review_count: 5,
		location_label: "Kimathi Street, Nyeri",
		opening_time: "08:00",
		closing_time: "18:00",
		open_days: "Mon - Sat",
		delivery_available: true,
	},
	{
		id: 2,
		slug: "preemie-tech",
		name: "Preemie",
		featured: true,
		categories: {
			name: "Electronics & Repair",
			color: "#2563eb",
			slug: "electronics-repair",
		},
		tagline: "Affordable phone, laptop, and accessory solutions.",
		cover_image:
			"https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1200&auto=format&fit=crop",
		average_rating: 3,
		review_count: 4,
		location_label: "Kenyatta Road, Nyeri",
		opening_time: "09:00",
		closing_time: "19:00",
		open_days: "Mon - Sun",
		delivery_available: true,
	},
	{
		id: 3,
		slug: "glow-house-salon",
		name: "Glow House Salon",
		featured: true,
		categories: {
			name: "Salon & Beauty",
			color: "#db2777",
			slug: "salon-beauty",
		},
		tagline: "Modern beauty care and professional styling.",
		cover_image:
			"https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.8,
		review_count: 28,
		location_label: "Gakere Road, Nyeri",
		opening_time: "08:30",
		closing_time: "20:00",
		open_days: "Mon - Sun",
		delivery_available: false,
	},
	{
		id: 4,
		slug: "royal-touch-barbershop",
		name: "Royal Touch Barbershop",
		featured: false,
		categories: {
			name: "Salon & Beauty",
			color: "#db2777",
			slug: "salon-beauty",
		},
		tagline: "Sharp cuts, clean fades, and premium grooming.",
		cover_image:
			"https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.5,
		review_count: 18,
		location_label: "Temple Road, Nyeri",
		opening_time: "09:00",
		closing_time: "21:00",
		open_days: "Tue - Sun",
		delivery_available: false,
	},
	{
		id: 5,
		slug: "green-basket-market",
		name: "Green Basket Market",
		featured: true,
		categories: {
			name: "Grocery & Supermarket",
			color: "#16a34a",
			slug: "grocery-supermarket",
		},
		tagline: "Fresh groceries and daily essentials.",
		cover_image:
			"https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.7,
		review_count: 42,
		location_label: "Othaya Road, Nyeri",
		opening_time: "07:00",
		closing_time: "22:00",
		open_days: "Mon - Sun",
		delivery_available: true,
	},
	{
		id: 6,
		slug: "family-choice-supermarket",
		name: "Family Choice Supermarket",
		featured: false,
		categories: {
			name: "Grocery & Supermarket",
			color: "#16a34a",
			slug: "grocery-supermarket",
		},
		tagline: "Convenient shopping with affordable prices.",
		cover_image:
			"https://images.unsplash.com/photo-1604719312566-8912e9227c6a?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.3,
		review_count: 21,
		location_label: "Mweiga Road, Nyeri",
		opening_time: "08:00",
		closing_time: "21:00",
		open_days: "Mon - Sat",
		delivery_available: true,
	},
	{
		id: 7,
		slug: "sparkle-laundry",
		name: "Sparkle Laundry",
		featured: true,
		categories: {
			name: "Laundry Services",
			color: "#0ea5e9",
			slug: "laundry",
		},
		tagline: "Fast, clean, and reliable laundry services.",
		cover_image:
			"https://images.unsplash.com/photo-1582735689369-4fe89db7114c?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.9,
		review_count: 33,
		location_label: "Kamakwa, Nyeri",
		opening_time: "07:30",
		closing_time: "19:00",
		open_days: "Mon - Sun",
		delivery_available: true,
	},
	{
		id: 8,
		slug: "quickwash-laundry",
		name: "QuickWash Laundry",
		featured: false,
		categories: {
			name: "Laundry Services",
			color: "#0ea5e9",
			slug: "laundry",
		},
		tagline: "Affordable washing, ironing, and dry cleaning.",
		cover_image:
			"https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.2,
		review_count: 15,
		location_label: "King'ong'o, Nyeri",
		opening_time: "08:00",
		closing_time: "18:00",
		open_days: "Mon - Sat",
		delivery_available: true,
	},
	{
		id: 9,
		slug: "codecraft-academy",
		name: "CodeCraft Academy",
		featured: true,
		categories: {
			name: "Education & Training",
			color: "#7c3aed",
			slug: "education",
		},
		tagline: "Programming and digital skills training.",
		cover_image:
			"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=1200&auto=format&fit=crop",
		average_rating: 5,
		review_count: 40,
		location_label: "Nyeri Town",
		opening_time: "08:00",
		closing_time: "17:00",
		open_days: "Mon - Fri",
		delivery_available: false,
	},
	{
		id: 10,
		slug: "future-stars-tuition",
		name: "Future Stars Tuition Centre",
		featured: false,
		categories: {
			name: "Education & Training",
			color: "#7c3aed",
			slug: "education",
		},
		tagline: "Quality tutoring and exam preparation classes.",
		cover_image:
			"https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=1200&auto=format&fit=crop",
		average_rating: 4.6,
		review_count: 24,
		location_label: "Ruring'u, Nyeri",
		opening_time: "09:00",
		closing_time: "16:00",
		open_days: "Mon - Sat",
		delivery_available: false,
	},
];

const dummyUserProfile = {
	avatar_url: "https://www.loremfaces.net/128/id/1.jpg",
	full_name: "Thompson Thompson",
	role: "user",
};

const dummyFavorites = [
	{ user_id: 1, business_id: 1 },
	{ user_id: 1, business_id: 5 },
];

export default {
	metadata,
	dummyPosts,
	dummyCategories,
	dummyBusinesses,
	dummyUserProfile,
	dummyFavorites,
};
